### PR TITLE
Adjustments to tests for https://github.com/stleary/JSON-java/pull/337

### PR DESCRIPTION
**Pull request by johnjaylward**

### CODE REVIEW

**Comment by stleary** [comment]
Thanks, will merge when https://github.com/stleary/JSON-java/pull/337 is merged.

**Comment by johnjaylward** [comment]
this one is for 337, not 336.

**Comment by stleary** [comment]
Sorry, just assumed this was the fix for the broken increment test in 336 (branch johnjaylward-fixSpelling), but I did not actually execute the test to make sure.

**Comment by johnjaylward** [comment]
#70 fixes the increment tests

**Comment by stleary** [comment]
Thanks, I think the comments and links are corrected now

**Comment by johnjaylward** [comment]
I believe these tests cover what we need.

**Comment by stleary** [comment]
OK to merge after stleary/JSON-java#337

**Pull request merged**
