### PR TITLE
Simplify number wrap fix

### PR DESCRIPTION
**Pull request by johnjaylward**
same tests as in #58, but updated for changes made in https://github.com/stleary/JSON-java/pull/272

### CODE REVIEW

**Comment by stleary** [comment]
@johnjaylward The JSON-Java changes have been merged. Do you want to fix the merge conflicts, or shall I push with the same changes you are proposing here, plus the merge conflict fixes?

**Comment by johnjaylward** [comment]
work is pretty busy now. If you can handle the merge conflicts that would be great.

**Comment by stleary** [comment]
No worries, will do.

**Comment by stleary** [comment]
Conflicts resolved in #60.

**Pull request closed without merging**
