### PR TITLE
Improving opt test to include missing values

### PR DESCRIPTION
**Pull request by quidryan**
Proves out https://github.com/stleary/JSON-java/issues/260

### CODE REVIEW

**Comment by stleary** [comment]
Will consider after the revert is completed. Thanks again for catching it.

**Comment by quidryan** [comment]
I wasn't following the previous work that had to be reverted, but wouldn't this test be relevant irrelevant to the state of the JSON-Java repo? This add coverage which did not exist before.

**Comment by stleary** [comment]
Well, the tests are not even included in the Maven repo. We keep them release-synced, so there is always a test release to match the JSON release, but there is no requirement for them to be timestamp-synced, if we are rushed.  Since @johnjaylward has also made a pull request in #55, we will proceed there. Please take a look at that branch and post if you see any tests that should be added.

**Comment by johnjaylward** [comment]
@quidryan , I basically did the same as you, but extended the tests to cover more opt methods in #55 

I believe my PR has more coverage than your even though we took the same approach. Let me know if you see anything else that needs to be added.

**Pull request closed without merging**
